### ISSUE TITLE
Customizations not working

### ISSUE THREAD

**Issue by RitvikSardana** [vpalcar/calendar_appbar#16]
![image](https://user-images.githubusercontent.com/65544983/179174806-e6aae8e4-4e7a-40b5-b2f4-4db4e138217a.png)

I am unable to change the background color when making it for browser, I can only see 3 Dates at time, how can I increase the no. of dates.

**Comment by nico671** [comment]
this currently isn't optimized for non mobile devices, weird behavior is to be expected on non mobile platforms
