### ISSUE TITLE
Got an Error in the package

### ISSUE THREAD

**Issue by JohnKinyanjui** [vpalcar/calendar_appbar#7]
**dependOnInheritedWidgetOfExactType<_LocalizationsScope>() or dependOnInheritedElement() was called before _CalendarAppBarState.initState() completed.
**

**Comment by vpalcar** [comment]
Hi there, could you add some more information, so I can reproduce the error? Cheers

**Comment by habibm94** [comment]
I got the same issue...

here is my code------------

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:calendar_appbar/calendar_appbar.dart';

class CalenderScreen extends StatefulWidget {
  @override
  _CalenderScreenState createState() => _CalenderScreenState();
}

class _CalenderScreenState extends State<CalenderScreen> {
  DateTime? selectedDate;
  void initState() {
    setState(() {
      selectedDate = DateTime.now();
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    
    return SafeArea(
        child: Scaffold(
      appBar: CalendarAppBar(
        onDateChanged: (value) =>
            (value) => setState(() => selectedDate = value),
        firstDate: DateTime.now().subtract(Duration(days: 140)),
        lastDate: DateTime.now(),
      ),
      floatingActionButton: FloatingActionButton(
        tooltip: 'Add Schedule Task',
        elevation: 30.0,
        backgroundColor: Color(0xFFDC011C9E),
        child: Icon(
          Icons.add,
          size: 44,
        ),
        onPressed: () {
          print('calender add got pressed');
        },
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.miniEndFloat,
      body: Container(
        color: Colors.white,
      ),
    ));
  }
}


here is the full error message-----

======== Exception caught by widgets library =======================================================
The following assertion was thrown building FlexibleSpaceBarSettings:
dependOnInheritedWidgetOfExactType<_LocalizationsScope>() or dependOnInheritedElement() was called before _CalendarAppBarState.initState() completed.

When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.

Typically references to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.

The relevant error-causing widget was: 
  Scaffold file:///C:/Users/habib/StudioProjects/__own_project/productivity_alpha/lib/screens/calender_screen.dart:23:16
When the exception was thrown, this was the stack: 
#0      StatefulElement.dependOnInheritedElement.<anonymous closure> (package:flutter/src/widgets/framework.dart:4821:9)
#1      StatefulElement.dependOnInheritedElement (package:flutter/src/widgets/framework.dart:4864:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3976:14)
#3      Localizations.localeOf (package:flutter/src/widgets/localizations.dart:415:48)
#4      _CalendarAppBarState._locale (package:calendar_appbar/calendar_appbar.dart:103:38)
...
====================================================================================================


will be very helpful i you can help here..thanks in advance

**Comment by vpalcar** [comment]
`locale: 'en'` should be the required attribute. The documentation will be fixed in the next package update. Thank you for reporting the problem.
